##Creating a Simple Neighbor-Joining tree with ape

##Install Packages, if necessary

install.packages("adegenet", dep=TRUE)
install.packages("phangorn", dep=TRUE)

##Load Packages

library(ape)
library(adegenet)
library(phangorn)

##Set working Directory

setwd("C:/Users/jerem/OneDrive/Desktop/Phylo-Local/Final Project May//")

##Import Data

dna <- fasta2DNAbin(file="Salmincola_COI_CleanIDs_AlignedMuscle.fasta")

##Compute Genetic Distances

D <- dist.dna(dna, model="TN93")

##Check Class and Length

class(D)
length(D)


##Get Neighbor-Joining Tree

tre <- nj(D)

##Ladderize Tree

tre <- ladderize(tre)

##Plot Simple Neighbor-Joining Tree

plot(tre, cex=.6)
title("A simple NJ tree")


plot(tre, show.tip=TRUE)
title("Unrooted NJ tree")


##Root the tree using the Achtheres species
##Root the tree with Achtheres as outgroup and Ladderize the Tree

tre2 <- root(tre, out="Achtheres.pimelodi.NY.1")
tre2 <- ladderize(tre2)

##Plot the Rooted Tree

plot(tre2, show.tip=TRUE, edge.width=1)
title("Rooted NJ tree")


##Creating a Maximum Parsimony Tree with Phygorn

##Convert Data to PhyDat format

dna2 <- as.phyDat(dna)
class(dna2)

##Check Object

dna2

##Create basic NJ tree
tre.ini <- nj(dist.dna(dna,model="raw"))
tre.ini

##Check Parsimony, Optimize Tree, Check optimized tree

parsimony(tre.ini, dna2)
tre.pars <- optim.parsimony(tre.ini, dna2, )
tre.pars

tre.pars.root <- root(phy = tre.pars, outgroup = "Achtheres.pimelodi.NY.1",
     resolve.root=TRUE, edgelabel=TRUE)

##Plot Tree

plot(tre.pars.root, type="phylogram", show.tip=TRUE, edge.width=2)
title("Maximum-parsimony tree")


##Algorithm advantages and disadvantages

##Software: NJ in ape
##Description: Generated a basic neighbor joining tree based on genetic distances
##using an aligned .fasta file.

##Strengths: Computationally simple, fast, does not search tree space

##Weaknesses: Little user input, branch lengths often incorrect/negative, rarely
##produces optimum tree, only approaches it. 
##Assumptions: Assumes the distances generated by MSA are accurate.

##User choices: The MSA used by the user may change the final tree depending on which method was used
##which may change perceived genetic distance. 

##Software: Max parsimony in phangorn

##Description: Generated a tree based on parsimony, minimizing the amount of evolutionary
##change required to build the tree.This uses branch lengths (based on mutations).

##assumptions: Rate of evolution is slow. Characters are independent among each other.

##downsides: Produce inconsistent trees in certain cases. i.e. adding more data does not
##necessarily cause the tree to approach a specific optimum tree
##Often greates simpler trees than biological reality, since pure parsimony is unlikely.

##Strengths: Parsimony is a reasonable assumption in evolutionary biology due to energentics
##Searches treespace so poor NJ trees can be ruled out.

##user choices: Can modify what character data is used. Can define outgroup.










